In [1]:
import numpy as np


x = np.array([1.0, 2.0, 3.0])
print(x)

[1. 2. 3.]


In [4]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
print(x + y)
print(type(x+y))

[3. 6. 9.]
<class 'numpy.ndarray'>


In [5]:
x * y

array([ 2.,  8., 18.])

In [6]:
x = np.array([1.0, 2.0, 3.0])
x / 2.0 # * broadcast

array([0.5, 1. , 1.5])

In [13]:
A = np.array([[1, 2], [3, 4]])
print(A)
print(A.shape)
print(type(A))
print(A.dtype)

[[1 2]
 [3 4]]
(2, 2)
<class 'numpy.ndarray'>
int64


In [16]:
A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])

A * B

array([[10, 40],
       [30, 80]])

In [21]:
X = np.array([[51, 55], [14, 19], [0, 4]])
print(X)
print(X[0])
print(X[0][1])

[[51 55]
 [14 19]
 [ 0  4]]
[51 55]
55


In [18]:
for row in X:
  print(row)

[51 55]
[14 19]
[0 4]


In [22]:
print(X)
X = X.flatten()
print(X)

[[51 55]
 [14 19]
 [ 0  4]]
[51 55 14 19  0  4]


In [26]:
print(type(X))
print(X[[0, 2, 4]])
print(X[np.array([0, 2, 4])])

<class 'numpy.ndarray'>
[51 14  0]
[51 14  0]


In [28]:
print(X > 15)
print(X[X > 15])

[ True  True False  True False False]
[51 55 19]
